src/main/java/com/studioalpha/model/Cliente.java
package com.studioalpha.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.validator.constraints.br.CNPJ;
import org.hibernate.validator.constraints.br.CPF;

import com.studioalpha.model.validation.FisicaGroup;
import com.studioalpha.model.validation.JuridicaGroup;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

@Entity
@Table(name="cliente")
public class Cliente implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private String nome;
	private String email;
	private String documentoReceitaFederal;
	private TipoPessoa tipo;
	private List<Endereco> enderecos = new ArrayList<>();

	@Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="cliente_sequence")
    @SequenceGenerator(name="cliente_sequence", sequenceName="cli_seq")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(nullable = false, length = 100)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(nullable = false, length = 255)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@CNPJ(groups = JuridicaGroup.class)
	@CPF(groups = FisicaGroup.class)
	@NotNull
	@Column(name="doc_receita_federal", nullable = false, length = 14)
	public String getDocumentoReceitaFederal() {
		return documentoReceitaFederal;
	}

	public void setDocumentoReceitaFederal(String documentoReceitaFederal) {
		this.documentoReceitaFederal = documentoReceitaFederal;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 10)
	public TipoPessoa getTipo() {
		return tipo;
	}

	public void setTipo(TipoPessoa tipo) {
		this.tipo = tipo;
	}

	@OneToMany(mappedBy="cliente", cascade=CascadeType.ALL)
	public List<Endereco> getEnderecos() {
		return enderecos;
	}

	public void setEnderecos(List<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente other = (Cliente) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/studioalpha/controller/CadastroClienteBean.java
package com.studioalpha.controller;

import java.io.Serializable;

import jakarta.faces.view.ViewScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

import com.studioalpha.model.Cliente;
import com.studioalpha.model.Endereco;
import com.studioalpha.model.TipoPessoa;
import com.studioalpha.service.CadastroClienteService;
import com.studioalpha.service.NegocioException;
import com.studioalpha.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Cliente cliente;
	
	private Endereco endereco;
	
	private boolean editandoEndereco;
	
	@Inject
	private CadastroClienteService cadastroClienteService;
	
	public void inicializar(){
		if (cliente == null) {
			limpar();
		}
	}
	
	public void limpar() {
		this.cliente = new Cliente();
		this.cliente.setTipo(TipoPessoa.FISICA);
	}
	
	public void salvar() {
		try {
			cadastroClienteService.salvar(cliente);
			limpar();
			
			FacesUtil.addInfoMessage("Cliente salvo com sucesso!");
		} catch(NegocioException e) {
			FacesUtil.addErrorMessage(e.getMessage());
		}
	}
	
	public void novoEndereco() {
		this.endereco = new Endereco();
		this.endereco.setCliente(this.cliente);
		this.editandoEndereco = false;
	}
	
	public void editarEndereco(Endereco endereco) {
		this.endereco = endereco;
		this.editandoEndereco = true;
	}
	
	public void excluirEndereco(Endereco endereco) {
		this.cliente.getEnderecos().remove(endereco);
	}
	
	public void confirmarEndereco() {
		if (!this.cliente.getEnderecos().contains(this.endereco)) {
			this.cliente.getEnderecos().add(this.endereco);
		}
	}
	
	public Endereco getEndereco() {
		return endereco;
	}
	
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}
	
	public Cliente getCliente() {
		return cliente;
	}
	
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
	
	public boolean isEditando() {
		return cliente != null && cliente.getId() == null;
	}
	
	public boolean isEditandoEndereco() {
		return editandoEndereco;
	}
	
	public TipoPessoa[] getTipos(){
		return TipoPessoa.values();
	}
}

src/main/java/com/studioalpha/controller/PesquisaClientesBean.java
package com.studioalpha.controller;

import jakarta.faces.view.ViewScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

import java.io.Serializable;
import java.util.List;

import com.studioalpha.model.Cliente;
import com.studioalpha.repository.Clientes;
import com.studioalpha.repository.filter.ClienteFilter;
import com.studioalpha.service.NegocioException;
import com.studioalpha.util.jsf.FacesUtil;

@Named
@ViewScoped
public class PesquisaClientesBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private Clientes clientes;
	
	private ClienteFilter filtro;
	private List<Cliente> clientesFiltrados;
	
	private Cliente clienteSelecionado;
	
	public PesquisaClientesBean() {
		filtro = new ClienteFilter();
	}
	
	public void pesquisar() {
		clientesFiltrados = clientes.filtrados(filtro);
	}
	
	public void excluir() {
		try {
			clientes.remover(clienteSelecionado);
			clientesFiltrados.remove(clienteSelecionado);
			
			FacesUtil.addInfoMessage("Cliente " + clienteSelecionado.getNome() + 
					" excluído com sucesso!");
		} catch (NegocioException e) {
			FacesUtil.addErrorMessage(e.getMessage());
		}
	}
	
	public List<Cliente> getClientesFiltrados() {
		return clientesFiltrados;
	}

	public ClienteFilter getFiltro() {
		return filtro;
	}

	public Cliente getClienteSelecionado() {
		return clienteSelecionado;
	}

	public void setClienteSelecionado(Cliente clienteSelecionado) {
		this.clienteSelecionado = clienteSelecionado;
	}
	
}

src/main/webapp/clientes/CadastroCliente.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui">

     <ui:define name="titulo">#{cadastroClienteBean.editando ? 'Edição de cliente' : 'Novo cliente'}</ui:define>
    
    <ui:define name="corpo">
    	<f:metadata>
    		<o:viewParam name="cliente" value="#{cadastroClienteBean.cliente}" />
    		<f:viewAction action="#{cadastroClienteBean.inicializar}" />
    	</f:metadata>

    	<h:form id="frm">
			<p:focus context="frm" />
			
	    	<h1>#{cadastroClienteBean.editando ? 'Edição de cliente' : 'Novo cliente'}</h1>
	    	
	    	<p:messages autoUpdate="true" closable="true" />
	    	
	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:button value="Novo" outcome="/clientes/CadastroCliente" />
	    			<p:commandButton value="Salvar" id="botaoSalvar"
	    				action="#{cadastroClienteBean.salvar}" update="@form"
	    				process="@this capaPanelGrid"
	    				validateClient="false" />
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    			<p:button value="Pesquisa" outcome="/clientes/PesquisaCliente" />
	    		</p:toolbarGroup>
	    	</p:toolbar>
	    	
	    	<p:panelGrid columns="2" id="capaPanelGrid" style="width: 100%; margin-top: 20px"
	    			columnClasses="rotulo, campo">
	    		<p:outputLabel value="Nome" for="nome"/>
	    		<p:inputText id="nome" size="60" maxlength="80" value="#{cadastroClienteBean.cliente.nome}" />
	    		
	    		<p:outputLabel value="E-mail" for="email"/>
	    		<p:inputText id="email" size="60" maxlength="80" value="#{cadastroClienteBean.cliente.email}" />
	    		
	    		<p:outputLabel value="Tipo:" for="tipo"/>
	    		<p:selectOneRadio id="tipo" value="#{cadastroClienteBean.cliente.tipo}">
	    			<f:selectItems value="#{cadastroClienteBean.tipos}" var="tipo" itemLabel="#{tipo.descricao}" 
	    				itemValue="#{tipo}"/>
	    			<p:ajax event="change" process="@this" update="documentoReceitaFederal documentoReceitaFederalLabel" />
	    		</p:selectOneRadio>	    		
	    		
	    		<p:outputLabel value="#{cadastroClienteBean.cliente.tipo.rotulo}" id="documentoReceitaFederalLabel" 
	    			for="documentoReceitaFederal"/>
	    		<p:inputMask id="documentoReceitaFederal" size="14" maxlength="14"
	    			mask="#{cadastroClienteBean.cliente.tipo.mascara}"
	    			converter="cpfCnpjMask" 
	    			value="#{cadastroClienteBean.cliente.documentoReceitaFederal}" >
	    			<f:validateBean validationGroups="#{cadastroClienteBean.cliente.tipo.grupoValidacao}" />	
    			</p:inputMask>   		
	    	</p:panelGrid>
	    	
	    	<p:commandButton value="Adicionar Endereço" actionListener="#{cadastroClienteBean.novoEndereco()}"
	    		process="@this" update="enderecoDialog" oncomplete="PF('enderecoDialogWidgetVar').show()"
	    		style="margin: 10px 0">
	    		<p:resetInput target="enderecoDialog" />	
    		</p:commandButton>
	    		
	    	<p:dataTable id="enderecoDataTable" value="#{cadastroClienteBean.cliente.enderecos}"
	    		var="endereco">
	    		<p:column headerText="Logradouro">
	    			<h:outputText value="#{endereco.logradouro}" />
	    		</p:column>
	    		<p:column headerText="Número" style="width: 100px">
	    			<h:outputText value="#{endereco.numero}" />
	    		</p:column>
	    		<p:column headerText="CEP" style="width: 100px">
	    			<h:outputText value="#{endereco.cep}" />
	    		</p:column>
	    		<p:column headerText="Cidade" style="width: 200px">
	    			<h:outputText value="#{endereco.cidade}" />
	    		</p:column>
	    		<p:column style="width: 100px; text-align: center">
	    			<p:commandButton icon="ui-icon-pencil" title="Editar"
	    				process="@this" update=":frm:enderecoPanelGroup"
	    				onsuccess="PF('enderecoDialogWidgetVar').show()"
	    				actionListener="#{cadastroClienteBean.editarEndereco(endereco)}">
	    				<p:resetInput target="enderecoDialog" />
    				</p:commandButton>
	    			
	    			<p:commandButton icon="ui-icon-trash" title="Excluir" process="@this"
	    				update="enderecoDataTable"
	    				action="#{cadastroClienteBean.excluirEndereco(endereco)}"></p:commandButton>
	    		</p:column>
	    	</p:dataTable>
	    		
	    	<p:dialog header="Inclusão de endereço" id="enderecoDialog" widgetVar="enderecoDialogWidgetVar"
	    		modal="true">
	    		<h:panelGroup id="enderecoPanelGroup">
	    			<p:messages id="enderecoMessages" autoUpdate="false" />
	    			
	    			<h:panelGrid columns="2">
	    				<p:outputLabel value="Logradouro" for="logradouro" />
	    				<p:inputText id="logradouro" size="60" maxlength="150" 
	    					value="#{cadastroClienteBean.endereco.logradouro}"/>
	    					
	    				<p:outputLabel value="Número" for="numero" />
	    				<p:inputText id="numero" size="10" maxlength="20" 
	    					value="#{cadastroClienteBean.endereco.numero}"/>
	    					
	    				<p:outputLabel value="CEP" for="cep" />
	    				<p:inputMask id="cep" size="15" 
	    					value="#{cadastroClienteBean.endereco.cep}"
	    					mask="99999-99"/>
	    					
	    				<p:outputLabel value="Cidade" for="cidade" />
	    				<p:inputText id="cidade" size="40" maxlength="60" 
	    					value="#{cadastroClienteBean.endereco.cidade}"/>
	    					
	    				<p:outputLabel value="UF" for="uf" />
	    				<p:inputText id="uf" size="10" maxlength="60" 
	    					value="#{cadastroClienteBean.endereco.uf}"/>
	    					
	    				<p:outputLabel />
	    				<p:commandButton value="#{cadastroClienteBean.editandoEndereco ? 'Alterar' : 'Incluir'}" 
	    					action="#{cadastroClienteBean.confirmarEndereco}"
	    					ignoreAutoUpdate="true"
	    					process="enderecoPanelGroup" update="enderecoPanelGroup enderecoDataTable"
	    					oncomplete="if (!args.validationFailed) PF('enderecoDialogWidgetVar').hide()"/>
	    			</h:panelGrid>
	    		</h:panelGroup>
	    	</p:dialog>
    	</h:form>
    </ui:define>
</ui:composition>

src/main/webapp/clientes/PesquisaCliente.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="titulo">Pesquisa de clientes</ui:define>
    
    <ui:define name="corpo">
    	<h:form id="frmPesquisa">
	    	<h1>Pesquisa de clientes</h1>
	    	
	    	<p:messages autoUpdate="true" closable="true" />
	    	
	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:commandButton value="Pesquisar" action="#{pesquisaClientesBean.pesquisar}"
	    				update="@form" />
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    			<p:button value="Novo" outcome="/clientes/CadastroCliente" />
	    		</p:toolbarGroup>
	    	</p:toolbar>
	    	
	    	<p:panelGrid columns="2" id="painel" style="width: 100%; margin-top: 20px"
	    			columnClasses="rotulo, campo">
	    		<p:outputLabel value="CPF/CNPJ" for="docReceitaFederal"/>
	    		<p:inputText id="docReceitaFederal" size="20" value="#{pesquisaClientesBean.filtro.documentoReceitaFederal}" />
	    		
	    		<p:outputLabel value="Nome" for="nome"/>
	    		<p:inputText id="nome" size="60" value="#{pesquisaClientesBean.filtro.nome}" />
	    	</p:panelGrid>
	    	
	    	<p:dataTable id="clientesTable" value="#{pesquisaClientesBean.clientesFiltrados}" var="cliente"
	    		style="margin-top: 20px" emptyMessage="Nenhum cliente encontrado." rows="20"
	    		paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom">
	    		
	    		<p:column headerText="Nome">
	    			<h:outputText value="#{cliente.nome}" />
	    		</p:column>
	    		<p:column headerText="Tipo" style="width: 250px">
	    			<h:outputText value="#{cliente.tipo.descricao}"/>
	    		</p:column>
	    		<p:column headerText="CPF/CNPJ" style="width: 300px">
	    			<h:outputText value="#{cliente.documentoReceitaFederal}" converter="cpfCnpjMask"/>
	    		</p:column>
	    		
	    		<p:column style="width: 100px; text-align: center">
	    			<p:button outcome="/clientes/CadastroCliente" icon="ui-icon-pencil" title="Editar">
	    				<f:param name="cliente" value="#{cliente.id}" />
	    			</p:button>
	    			<p:commandButton icon="ui-icon-trash" title="Excluir" oncomplete="PF('confirmacaoExclusao').show()"
	    					process="@this" update=":frmPesquisa:confirmacaoExclusaoDialog">
	    				<f:setPropertyActionListener target="#{pesquisaClientesBean.clienteSelecionado}" value="#{cliente}" />
	    			</p:commandButton>
	    		</p:column>
	    		
	    	</p:dataTable>
	    	
	    	<p:confirmDialog header="Exclusão de cliente" 
	    		message="Tem certeza que deseja excluir o cliente #{pesquisaClientesBean.clienteSelecionado.nome}?"
	    		widgetVar="confirmacaoExclusao"	id="confirmacaoExclusaoDialog">
	    		<p:button value="Não" onclick="PF('confirmacaoExclusao').hide(); return false;" />
	    		<p:commandButton value="Sim" oncomplete="PF('confirmacaoExclusao').hide();"
	    			action="#{pesquisaClientesBean.excluir}" process="@this"
	    			update=":frmPesquisa:clientesTable" id="yesButton" />
	    	</p:confirmDialog>
    	</h:form>
    </ui:define>
</ui:composition>